### ISSUE TITLE
SQL error while whitelisting

### ISSUE THREAD

**Issue by wtrdk** [lbausch/SQLgreyGUI#10]
While registering I get a few mails from spotify that are greylisted. When I try to whitelist them, the first one is whitelisted, all the others give this error:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '208.117.49-news.spotifymail.com-bounces+898596-add9-user=domain.' for key 'PRIMARY' (SQL: insert into `from_awl` (`sender_name`, `sender_domain`, `src`, `first_seen`, `last_seen`) values (bounces+898596-add9-user=domain.nl, news.spotifymail.com, 208.117.49, 2016-02-08 11:19:05, 2016-02-08 11:19:05))

Can you help me?

**Comment by lbausch** [comment]
Thank you for reporting this issue - I will look into it as soon as I have some spare time. :)

**Comment by lbausch** [comment]
This should be fixed with the latest release (v2.0.0). Please consider upgrading. :)
