### ISSUE TITLE
Instalation errors

### ISSUE THREAD

**Issue by alkar1** [lbausch/SQLgreyGUI#18]
`root@rex:/var/www/SQLgreyGUI# npm update laravel-mix
root@rex:/var/www/SQLgreyGUI# npm install && npm run prod
npm WARN lifecycle undefined~postinstall: cannot run in wd %s %s (wd=%s) undefined yarn run prod /var/www/SQLgreyGUI
up to date in 12.943s

> @ prod /var/www/SQLgreyGUI
> npm run production

> @ production /var/www/SQLgreyGUI
> cp resources/assets/js/vue-strap/utils.js node_modules/vue-strap/src/utils/utils.js && cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 ERROR  Failed to compile with 3 errors                                                            18:56:13

These dependencies were not found:

* /var/www/SQLgreyGUI/resources/assets/js/app.js in multi ./resources/assets/js/app.js ./resources/assets/sass/style.scss
* /var/www/SQLgreyGUI/resources/assets/js/public.js in multi ./resources/assets/js/public.js
* /var/www/SQLgreyGUI/resources/assets/sass/style.scss in multi ./resources/assets/js/app.js ./resources/assets/sass/style.scss

To install them, you can run: npm install --save /var/www/SQLgreyGUI/resources/assets/js/app.js /var/www/SQLgreyGUI/resources/assets/js/public.js /var/www/SQLgreyGUI/resources/assets/sass/style.scss
          Asset       Size  Chunks                    Chunk Names
  /js/vendor.js     432 kB       0  [emitted]  [big]  /js/vendor
  /js/public.js  147 bytes       1  [emitted]         /js/public
     /js/app.js  250 bytes       2  [emitted]         /js/app
/js/manifest.js    1.39 kB       3  [emitted]         /js/manifest
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ production: `cp resources/assets/js/vue-strap/utils.js node_modules/vue-strap/src/utils/utils.js && cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-11T16_56_13_877Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ prod: `npm run production`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-11T16_56_13_892Z-debug.log
root@rex:/var/www/SQLgreyGUI#
`

**Comment by lbausch** [comment]
It seems like you're missing some npm dependencies. Please refer to the docs for installation instructions.

**Comment by alkar1** [comment]
Thanks for reply.Helped reinstall.
