### ISSUE TITLE
requires 0.0.9 stolz/assets instead of dev-master

### ISSUE THREAD

**Issue by gruzilla** [lbausch/SQLgreyGUI#2]
thanks for this gem!

running `composer.phar update` results in

``
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'Stolz\\Assets\\ManagerServiceProvider' not found","file":"\/home\/ma\/public_html\/web\/sqlgreygui\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/ProviderRepository.php","line":157}}Script php artisan clear-compiled handling the post-update-cmd event returned with an error
``

after changing composer.json to:

``
    "require": {
        "laravel/framework": "4.2.*",
        "rcrowe/twigbridge": "0.6.*",
        "stolz/assets": "0.0.9",
        "components/jquery": "1.11.*@dev",
``

it worked.

**Comment by lbausch** [comment]
Thank you for opening this issue - I will update composer dependencies soon.

**Comment by lbausch** [comment]
fxd.
