### ISSUE TITLE
Compatible nginx?

### ISSUE THREAD

**Issue by MisterM74** [lbausch/SQLgreyGUI#5]
hello
Do you have a config Nginx on the subject?
thank you
mz

**Comment by lbausch** [comment]
The default config shipped with Nginx should do the trick. For pretty URLs please check the official Laravel documentation:
http://laravel.com/docs/5.0/installation#pretty-urls

Let me know if this works for you.

**Comment by MisterM74** [comment]
I will test the application
Do you have a "good" tutorial on installing SQLgrey?
Many greetings
Michel

**Comment by lbausch** [comment]
Nope, sorry. But it should'nt be that hard as most distributions provide packages for sqlgrey.

**Comment by MisterM74** [comment]
good evening
To configure the package, it's OK for my part, now, if I have a problem I would return to the message.
I test under nginx, I also come back if I have a concern
thank you
Mz
