### ISSUE TITLE
Config Nginx

### ISSUE THREAD

**Issue by MisterM74** [lbausch/SQLgreyGUI#6]
Hello
Config Nginx

server {
        listen 80;

        server_name domain.com ;

        root   /var/www/domain.com/web/public;

        index index.html index.htm index.php index.cgi index.pl index.xhtml;

	error_log /var/log/nginx/sqlgreygui-error.log;
        access_log /var/log/nginx/sqlgreygui-access.log combined;

	location / {
		include /etc/nginx/nbs.rules;
		try_files $uri $uri/ /index.php?$query_string;
	}

	location ~ \.php$ {
            try_files /2998dc8fd5163833957da292dc5b3062.htm @php;
        }

        location @php {
	    include /etc/nginx/fastcgi_params;
            fastcgi_pass unix:/var/run/php5-fpm.sock;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            #fastcgi_intercept_errors on;
        }
}

Mz

**Comment by lbausch** [comment]
Thank you. I will check and see if I can make this a part of extended installation instructions.
