### ISSUE TITLE
Error after install: Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by wtrdk** [lbausch/SQLgreyGUI#9]
Hi,

I would love to use SQLgreyGUI, but after installation I go to the URL and get this message:
Whoops, looks like something went wrong.

My .env file looks like this:
```
APP_ENV=production
APP_DEBUG=false
APP_URL=http://myurl:80
APP_TIMEZONE=Europe/Amsterdam
APP_KEY=23456kjhg34j653g51234565645

# database for SQLgreyGUI
# if you want to use a single database for both SQLgreyGUI and SQLgrey
# use only this config block
DB_HOST=localhost
DB_DATABASE=sqlgrey
DB_USERNAME=sqlgrey
DB_PASSWORD=**********

# Uncomment the following lines if SQLgrey resides in a different database
#SQLGREY_DB_HOST=null
#SQLGREY_DB_DATABASE=null
#SQLGREY_DB_USERNAME=null
#SQLGREY_DB_PASSWORD=null

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

MAIL_DRIVER=mail
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

ASSETS_PIPELINE=auto
```
I use Ubuntu Server 14.04, Apache2 and Mysql
During the installation there were no errors.

Can you help me?

**Comment by wtrdk** [comment]
I found the solution using the debug=true flag. I had to insert the APPKEY 32 character key also in config\app.php.
Now it works like a charm!

**Comment by lbausch** [comment]
This shouldn't be necessary. You might try to run `php artisan cache:clear` and see if this also solves your problem.
